Traceback (most recent call last):
  File "/home/data/nbc/athena/athena/run_cv.py", line 553, in <module>
    run_para(data_dir, out_dir)
  File "/home/data/nbc/athena/athena/run_cv.py", line 530, in run_para
    raise Exception()
Exception
